name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install & Build
        run: |
          # Ye command check karegi ke index.html kahan chhupi hai
          FILEPATH=$(find . -name index.html -path "*/public/*" | head -n 1)
          if [ -z "$FILEPATH" ]; then echo "Error: index.html not found anywhere!"; exit 1; fi
          
          # Folder ke andar ghusne ke liye
          ROOT_DIR=$(echo $FILEPATH | sed 's/\/public\/index.html//')
          cd $ROOT_DIR
          
          npm install --force
          CI=false npm run build

      - name: Build APK
        run: |
          # Android folder dhoond kar build shuru karein
          ANDROID_DIR=$(find . -name gradlew -path "*/android/*" | head -n 1 | sed 's/\/gradlew//')
          cd $ANDROID_DIR
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AttendX-APK
          path: "**/app-debug.apk"
